# Generated by Django 5.2.5 on 2025-08-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Upload an image for the project card (e.g., project-creative.jpg)', upload_to='project_images/')),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g., fas fa-globe)', max_length=50)),
                ('image', models.ImageField(help_text='Upload an image for the service card (e.g., service-webdev.jpg)', upload_to='service_images/')),
                ('description', models.TextField()),
                ('cost', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.TextField(help_text='Comma-separated list of features (e.g., Feature 1, Feature 2)')),
            ],
        ),
    ]
